### PR TITLE
Feature/reassign owner on delete

### PR DESCRIPTION
**Pull request by frankfarrell**
Create database not in transaction. 
Reassign owner of resources on delete. 

@stephenpaulger

### CODE REVIEW

**Comment by stephenpaulger** [comment]
The lack of `REASSIGN USER` is annoying!

I think instead of

    func GetUsersnamesForUsesysid(tx *sql.Tx, db *sql.DB, usersIdsInterface []interface{}) []string

You could a single method interface that allows anything with a `Query` (*15 mins later*) and that interface is already defined in `database/sql/driver` which would allow the function definition to be

    func GetUsersnamesForUsesysid(q *driver.Queryer, usersIdsInterface []interface{}) []string

which in turn would allow you to replace

	if tx != nil {
		txrows, txerr := tx.Query(selectUserQuery)
		rows = txrows
		err = txerr
	} else {
		dbrows, dberr := db.Query(selectUserQuery)
		rows = dbrows
		err = dberr
	}

with

    rows, err := q.Query(selectUserQuery)

**Comment by frankfarrell** [comment]
Thanks for figuring that out, I knew there must be something like that around!

**Comment by frankfarrell** [comment]
I couldn't get this to work. Probably dont understand go enough, but is this 
```
func (tx *Tx) Query(query string, args ...interface{}) (*Rows, error) {
	return tx.QueryContext(context.Background(), query, args...)
}
```
an implementation of this: 
```
type Queryer interface {
	Query(query string, args []Value) (Rows, error)
}
``` ?

**Comment by stephenpaulger** [comment]
It doesn't look like it.

I think I may have been hasty suggesting that interface as it looks to be deprecated.

I'll try to have another look at this tomorrow, looking at the different types all called Tx in lib/pq, database/sql and database/sql/drivers has me going round in circles.

**Comment by stephenpaulger** [comment]
It looks like you could define your own `Queryer` interface.

    type Queryer interface {
        Query(query string, args ...interface{}) (*Rows, error)
    }

As the `Query` definition in database/sql for Tx and DB are both the same.

**Pull request merged**
